

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_cron" WITH SCHEMA "pg_catalog";






CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."Status" AS ENUM (
    'paid',
    'unpaid',
    'overdue'
);


ALTER TYPE "public"."Status" OWNER TO "postgres";


COMMENT ON TYPE "public"."Status" IS 'Invoice Status enum';



CREATE TYPE "public"."customerStatus" AS ENUM (
    'active',
    'inactive'
);


ALTER TYPE "public"."customerStatus" OWNER TO "postgres";


COMMENT ON TYPE "public"."customerStatus" IS 'Customer active inactive state';



CREATE TYPE "public"."sex" AS ENUM (
    'male',
    'female',
    'other'
);


ALTER TYPE "public"."sex" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_customer_last_purchase"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    -- Log the values being used
    RAISE NOTICE 'Trigger fired for customer_id: %, created_at: %', NEW.customer_id, NEW.created_at;

    -- Check if the customer exists
    IF NOT EXISTS (SELECT 1 FROM customers WHERE customer_id = NEW.customer_id) THEN
        RAISE EXCEPTION 'Customer with customer_id % does not exist', NEW.customer_id;
    END IF;

    -- Update the last_purchase for the customer
    UPDATE customers
    SET last_purchase = NEW.created_at
    WHERE customer_id = NEW.customer_id;

    -- Log the result of the update
    IF FOUND THEN
        RAISE NOTICE 'Updated last_purchase for customer_id: % to %', NEW.customer_id, NEW.created_at;
    ELSE
        RAISE NOTICE 'No update needed for customer_id: %', NEW.customer_id;
    END IF;

    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_customer_last_purchase"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."invoices" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "description" "text",
    "total" numeric DEFAULT 0.00 NOT NULL,
    "status" "public"."Status" DEFAULT 'unpaid'::"public"."Status" NOT NULL,
    "customer_id" "uuid" NOT NULL,
    "due_date" "date",
    "owner_id" "uuid" DEFAULT "auth"."uid"(),
    "quantity" integer DEFAULT 1 NOT NULL,
    "unit_price" real DEFAULT '0'::real NOT NULL
);


ALTER TABLE "public"."invoices" OWNER TO "postgres";


COMMENT ON COLUMN "public"."invoices"."description" IS 'Description of the invoice';



COMMENT ON COLUMN "public"."invoices"."total" IS 'Amount';



COMMENT ON COLUMN "public"."invoices"."status" IS 'Status of the invoice';



COMMENT ON COLUMN "public"."invoices"."due_date" IS 'Due date of the invoice';



ALTER TABLE "public"."invoices" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Invoices_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."customers" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "customer_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text",
    "phone" "text" DEFAULT ''::"text" NOT NULL,
    "sex" "public"."sex" DEFAULT 'male'::"public"."sex",
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "email" "text",
    "address" "text",
    "last_purchase" timestamp with time zone,
    "status" "public"."customerStatus" DEFAULT 'active'::"public"."customerStatus" NOT NULL
);


ALTER TABLE "public"."customers" OWNER TO "postgres";


COMMENT ON TABLE "public"."customers" IS 'Customers table';



COMMENT ON COLUMN "public"."customers"."name" IS 'name of the customer';



COMMENT ON COLUMN "public"."customers"."phone" IS 'Customer phone';



COMMENT ON COLUMN "public"."customers"."sex" IS 'Customer Sex';



COMMENT ON COLUMN "public"."customers"."user_id" IS 'Owner user id';



COMMENT ON COLUMN "public"."customers"."address" IS 'Address of the customer';



COMMENT ON COLUMN "public"."customers"."last_purchase" IS 'The last invoice date for the customer';



CREATE TABLE IF NOT EXISTS "public"."payments" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "customer_id" "uuid" NOT NULL,
    "invoice_id" bigint NOT NULL
);


ALTER TABLE "public"."payments" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."suppliers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" DEFAULT ''::"text" NOT NULL
);


ALTER TABLE "public"."suppliers" OWNER TO "postgres";


ALTER TABLE "public"."suppliers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."suppliers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."invoices"
    ADD CONSTRAINT "Invoices_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_customer_id_key" UNIQUE ("customer_id");



ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_phone_key" UNIQUE ("phone");



ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_pkey" PRIMARY KEY ("customer_id", "phone");



ALTER TABLE ONLY "public"."payments"
    ADD CONSTRAINT "payments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."suppliers"
    ADD CONSTRAINT "suppliers_pkey" PRIMARY KEY ("id");



CREATE INDEX "customers_user_id_idx" ON "public"."customers" USING "btree" ("user_id");



CREATE INDEX "invoices_customer_id_idx" ON "public"."invoices" USING "btree" ("customer_id");



CREATE INDEX "payments_customer_id_idx" ON "public"."payments" USING "btree" ("customer_id");



CREATE INDEX "payments_invoice_id_idx" ON "public"."payments" USING "btree" ("invoice_id");



CREATE OR REPLACE TRIGGER "customer_last_purchase" AFTER INSERT ON "public"."invoices" FOR EACH ROW EXECUTE FUNCTION "public"."update_customer_last_purchase"();



ALTER TABLE ONLY "public"."invoices"
    ADD CONSTRAINT "invoices_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("customer_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."payments"
    ADD CONSTRAINT "payments_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("customer_id");



ALTER TABLE ONLY "public"."payments"
    ADD CONSTRAINT "payments_invoice_id_fkey" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id");



CREATE POLICY "Allow users to update their own records" ON "public"."customers" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable delete for users based on user_id" ON "public"."customers" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable insert for authenticated users only" ON "public"."customers" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable users to view their own data only" ON "public"."customers" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Full CRUD for owner" ON "public"."invoices" USING ((( SELECT "auth"."uid"() AS "uid") = "owner_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "owner_id"));



ALTER TABLE "public"."customers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."invoices" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."payments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."suppliers" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";









































































































































































































GRANT ALL ON FUNCTION "public"."update_customer_last_purchase"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_customer_last_purchase"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_customer_last_purchase"() TO "service_role";
























GRANT ALL ON TABLE "public"."invoices" TO "anon";
GRANT ALL ON TABLE "public"."invoices" TO "authenticated";
GRANT ALL ON TABLE "public"."invoices" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Invoices_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Invoices_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Invoices_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."customers" TO "anon";
GRANT ALL ON TABLE "public"."customers" TO "authenticated";
GRANT ALL ON TABLE "public"."customers" TO "service_role";



GRANT ALL ON TABLE "public"."payments" TO "anon";
GRANT ALL ON TABLE "public"."payments" TO "authenticated";
GRANT ALL ON TABLE "public"."payments" TO "service_role";



GRANT ALL ON TABLE "public"."suppliers" TO "anon";
GRANT ALL ON TABLE "public"."suppliers" TO "authenticated";
GRANT ALL ON TABLE "public"."suppliers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."suppliers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."suppliers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."suppliers_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























